[package]
name = "test_zed"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
rope = { path = "./crates/zed/crates/rope" }
sum_tree = { path = "./crates/zed/crates/sum_tree" }
text = { path = "./crates/zed/crates/text" }
clock = { path = "./crates/zed/crates/clock" }
language = { path = "./crates/zed/crates/language" }
multi_buffer = { path = "./crates/zed/crates/multi_buffer" }
collections = { path = "./crates/zed/crates/collections" }
settings = { path = "./crates/zed/crates/settings" }
theme = { path = "./crates/zed/crates/theme" }
util = { path = "./crates/zed/crates/util" }
syntect = { git = "https://github.com/trishume/syntect" }
onig = { version = "6.5.2", default-features = false }
smol = "2.0.2"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
rand = "0.8.5"
log = "0.4"
unicode-segmentation = "1.12.0"
ui = { path = "./crates/zed/crates/ui" }
smallvec = "1.13"
libloading = "0.9.0"
tree-sitter = "0.26"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.1"
tree-sitter-css = "0.23"
tree-sitter-go = "0.25"
tree-sitter-html = "0.23"
tree-sitter-javascript = "0.25"
tree-sitter-json = "0.24"
tree-sitter-python = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-typescript = "0.23"
tree-sitter-zig = "1.1.2"
tree-sitter-java = "0.23.5"
tree-sitter-c-sharp = "0.23.5"
tree-sitter-cpp = "0.23.4"
tree-sitter-php = "0.24.2"
tree-sitter-lua = "0.5.0"
tree-sitter-ruby = "0.23.1"
tree-sitter-dart = "0.2.0"
tree-sitter-swift = "0.7.3"
tree-sitter-r = "1.3.0"
tree-sitter-powershell = "0.26.4"
tree-sitter-asm = "0.24.0"
tree-sitter-groovy = "0.1.2"
