[package]
name = "test_zed"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
rope = { path = "./crates/zed/crates/rope" }
sum_tree = { path = "./crates/zed/crates/sum_tree" }
text = { path = "./crates/zed/crates/text" }
clock = { path = "./crates/zed/crates/clock" }
syntect = { git = "https://github.com/trishume/syntect" }
