[package]
name = "dzd"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
fancy-regex.workspace = true
ratatui = "0.29.0"
rope = { path = "../rope" }
sum_tree = { path = "../sum_tree" }
# syntect = "5.2.0"
syntect = { git = "https://github.com/trishume/syntect" }
text = { path = "../text" }

[lints]
workspace = true
